apiVersion: extensions/v1betal
kind: Deployment
metadata:
 name: sample-deploy
spec:
 replicas: 10
 template:
  metadata:
   labels:
    app: sample-app
 spec:
  containers:
  -name: sample-pod
   image: devopstrainer1/test2:latest
   ports:
   -containerPort: 80
